import asyncio
import logging
from pathlib import Path
from typing import Any
from urllib import parse as urlparse

import tomlkit
from packageurl import PackageURL
from packaging.markers import Marker

from hermeto.core.checksum import ChecksumInfo, must_match_any_checksum
from hermeto.core.config import get_config
from hermeto.core.errors import LockfileNotFound, PackageRejected
from hermeto.core.models.input import Request
from hermeto.core.models.output import EnvironmentVariable, RequestOutput, ProjectFile
from hermeto.core.models.property_semantics import PropertySet
from hermeto.core.models.sbom import Component, create_backend_annotation
from hermeto.core.package_managers.general import async_download_files
from hermeto.core.rooted_path import RootedPath
from hermeto.core.package_managers.pip.main import _check_metadata_in_sdist
from hermeto.core.package_managers.pip.package_distributions import WheelsFilter

log = logging.getLogger(__name__)

UV_LOCK_FILE = "uv.lock"

def fetch_uv_source(request: Request) -> RequestOutput:
    components: list[Component] = []
    project_files: list[ProjectFile] = []
    
    environment_variables: list[EnvironmentVariable] = [
        EnvironmentVariable(name="UV_FIND_LINKS", value="${output_dir}/deps/uv"),
        EnvironmentVariable(name="UV_NO_INDEX", value="true"),
        EnvironmentVariable(name="UV_OFFLINE", value="true"),
    ]

    uv_deps_dir = request.output_dir.join_within_root("deps", "uv")
    uv_deps_dir.path.mkdir(parents=True, exist_ok=True)

    packages = getattr(request, "uv_packages", getattr(request, "packages", []))

    for package in packages: 
        package_path = request.source_dir.join_within_root(package.path)
        uv_lock_path = package_path.join_within_root(UV_LOCK_FILE)

        if not uv_lock_path.path.exists():
            raise LockfileNotFound(
                files=uv_lock_path.path,
                solution="Ensure uv.lock is checked into the repository. Hermeto requires a strict lockfile."
            )

        log.info("Parsing static lockfile %s to prevent Arbitrary Code Execution", uv_lock_path)
        parsed_deps = _parse_uv_lock(uv_lock_path, uv_deps_dir, request)

        _download_uv_artifacts_sync(parsed_deps, uv_deps_dir)

        for dep in parsed_deps:
            if dep.get("is_local_workspace", False):
                log.info("Skipping network fetch for local workspace package: %s", dep["name"])
                continue

            try:
                must_match_any_checksum(dep["download_path"], [dep["checksum_info"]])
            except PackageRejected:
                dep["download_path"].unlink(missing_ok=True)
                raise PackageRejected(
                    f"Checksum mismatch for {dep['name']}. Dropping payload to preserve sandbox integrity."
                )

            if dep["package_type"] == "sdist":
                _check_metadata_in_sdist(dep["download_path"])

            purl = _generate_purl_dependency(dep)
            
            components.append(
                Component(
                    name=dep["name"],
                    version=dep["version"],
                    purl=purl,
                    properties=PropertySet(
                        pip_package_binary=(dep["package_type"] == "wheel"),
                        pip_build_dependency=False, 
                        found_by="uv"               
                    ).to_properties(),
                )
            )
        
        export_lines = [
            "# Generated by Hermeto (Path B: Export Bridge)",
            "--no-index"
        ]
        
        for dep in parsed_deps:
            if dep.get("is_local_workspace"):
                continue 
            
            req_line = f"{dep['name']}=={dep['version']}"
            if dep.get("markers"):
                req_line += f" ; {dep['markers']}"
            
            export_lines.append(req_line)

        export_content = "\n".join(export_lines) + "\n"
        
        export_file_path = request.output_dir.join_within_root("hermeto-uv-export.txt").path
        
        export_file_path.write_text(export_content)
        
        log.info("Successfully wrote Export Bridge file at %s", export_file_path.name)
        
        project_files.append(
            ProjectFile(
                abspath=export_file_path.resolve(),
                template=export_content
            )
        )
        
    annotations = []
    if backend_annotation := create_backend_annotation(components, "uv"):
        annotations.append(backend_annotation)

    return RequestOutput.from_obj_list(
        components=components,
        environment_variables=environment_variables,
        project_files=project_files,
        annotations=annotations,
    )

def _parse_uv_lock(lock_path: RootedPath, deps_dir: RootedPath, request: Request) -> list[dict[str, Any]]:
    with open(lock_path.path, "r") as f:
        lock_data = tomlkit.load(f)

    packages = lock_data.get("package", [])
    parsed_deps = []

    req_options = getattr(request, "options", {})
    wheel_filter = req_options.get("binary_filters") if req_options else None
    prefer_binary = req_options.get("prefer_binary", False) if req_options else False
    target_env = req_options.get("target_env") if req_options else None

    for pkg in packages:
        name = pkg.get("name")
        version = pkg.get("version")

        markers_string = pkg.get("markers")
        if markers_string:
            try:
                marker = Marker(markers_string)
                target_env = req_options.get("target_env")
                if target_env is not None:
                    if not marker.evaluate(target_env):
                        log.debug("Skipping %s: marker '%s' evaluated to False", name, markers_string)
                        continue
            except Exception as e:
                log.warning("Failed to parse PEP 508 marker for %s: %s", name, e)
        
        source = pkg.get("source", {})
        if "directory" in source or "editable" in source:
            parsed_deps.append({"name": name, "version": version, "is_local_workspace": True})
            continue

        target_url = None
        target_hash = None
        pkg_type = None

        if "sdist" in pkg and not prefer_binary:
            sdist = pkg["sdist"]
            target_url = sdist.get("url")
            target_hash = sdist.get("hash")
            pkg_type = "sdist"
        
        elif "wheels" in pkg:
            wheels = pkg.get("wheels", [])
            selected_wheel = _select_best_wheel(wheels, wheel_filter)
            
            if not selected_wheel:
                raise PackageRejected(f"No compatible wheel found for {name}=={version}")
            
            target_url = selected_wheel.get("url")
            target_hash = selected_wheel.get("hash")
            pkg_type = "wheel"
            
        if target_url and target_hash:
            filename = Path(urlparse.urlparse(target_url).path).name
            download_path = deps_dir.join_within_root(filename).path
            
            parsed_deps.append({
                "name": name,
                "version": version,
                "fetch_url": target_url,
                "download_path": download_path,
                "checksum_info": ChecksumInfo.from_hash(target_hash),
                "package_type": pkg_type,
                "is_local_workspace": False,
                "markers": markers_string 
            })

    return parsed_deps

def _select_best_wheel(wheels: list[dict], wheel_filter: WheelsFilter | None) -> dict | None:
    if not wheels:
        return None
    
    if not wheel_filter:
        return wheels[0]

    for wheel in wheels:
        url = wheel.get("url", "")
        filename = Path(urlparse.urlparse(url).path).name
        
        if wheel_filter.matches(filename):
            return wheel
            
    return None

def _download_uv_artifacts_sync(parsed_deps: list[dict[str, Any]], deps_dir: RootedPath) -> None:
    files_to_download = {}
    
    for dep in parsed_deps:
        if dep.get("is_local_workspace"):
            continue
            
        if not dep["download_path"].exists():
            files_to_download[dep["fetch_url"]] = dep["download_path"]

    if files_to_download:
        log.info("Prefetching %d isolated artifacts for uv...", len(files_to_download))
        asyncio.run(async_download_files(files_to_download, get_config().runtime.concurrency_limit))

def _generate_purl_dependency(dep: dict[str, Any]) -> str:
    qualifiers = {}
    if "checksum_info" in dep:
        qualifiers["checksum"] = str(dep["checksum_info"])
    
    purl = PackageURL(
        type="pypi",
        name=dep["name"],
        version=dep["version"],
        qualifiers=qualifiers
    )
    return purl.to_string()